name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm i downdoc
      - run: find docs -name '*.adoc' -exec npx downdoc {} \;
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs_puml
      - run: echo "::add-mask::$PLANTUML_SERVER"
      - run: |
          sed -i "s#puml_url:.*#puml_url: $PLANTUML_SERVER#g" mkdocs.yml
        env:
          PLANTUML_SERVER: ${{ secrets.PLANTUML_SERVER }}
      - run: mkdocs gh-deploy --force
